---
driver:
  name: vagrant
  network:
#  - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: debian-7.11
#  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[zabbix3::default]
      - recipe[zabbix3::repository]
      - recipe[zabbix3::mysql]
      - recipe[zabbix3::server]
      - recipe[zabbix3::agent]
      - recipe[zabbix3::frontend]
    attributes:
